### ISSUE TITLE
Rolling Release Installation

### ISSUE THREAD

**Issue by AleTassi** [social-manager-tools/instagram-bot.js#101]
### Versions

Replace the values below with your own:

- **Bot Version:** v1.0.0
- **Node Version: v8.12 (Bot require >= 7.6)
- **Operating System: Windows 10 home
- **Browser: Google Chrome 64

### Expected Behavior

Running `npm install` should install dependency.

### Actual Behavior

got those warning in console running `npm install`
```
    npm WARN Invalid version: "roling-release"
    npm WARN instagram-bot.js-rolling-release-v1 No description
    npm WARN instagram-bot.js-rolling-release-v1 No repository field.
    npm WARN instagram-bot.js-rolling-release-v1 No README data
    npm WARN instagram-bot.js-rolling-release-v1 No license field.

    up to date in 1.431s
    found 0 vulnerabilities
```
running `node bot.js` i got this

    Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\aleta\Desktop\stuff\instagram-bot.js-rolling-release-v1\bot.js:28:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

running `npm run clean` i got this 
```
npm ERR! Invalid version: "roling-release"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aleta\AppData\Roaming\npm-cache\_logs\2018-09-27T10_19_41_664Z-debug.log
```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. `npm install`
2. `node bot.js`

### config.js (remember to remove password)
```
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "", // without @
    "instagram_password": "",
    "instagram_hashtag": ["", "", ""], //without #, raccomanded more than 20
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 800,      // work only in likemode_classic
    "bot_likeday_max": 900,      // work only in likemode_classic. In 2018 limit instagram is 1000/day
    "bot_sleep_night": false,    // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
    "bot_userwhitelist": ["user1", "user2", "user3"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["comment1", "comment2", "comment3"],
        }
    },
    "likemode_competitor_users": {
        "account": "user_nickname" // without @
    },

    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "/usr/bin/chromium-browser", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};

```

**Comment by ptkdev** [comment]
Hi, sorry my fault. 
But in your report you not run `npm install`
And for run bot you need use: `node bot.js --config="./configs/config.js"`

# Docker setup (new version)
If you prefer to run this using Docker, an official container is available from the [Docker Hub](https://hub.docker.com/r/socialmanagertools/instagram-bot.js).

In order to run it, copy the `config.js.tpl` file, configure it as you prefer, then use it through volume mapping,
like in this example:

```sh
$ docker run \
    --restart=always \
    --name=instagram-bot \
    -d \
    -v /path/to/config.js:/app/configs/config.js \
    socialmanagertools/instagram-bot.js &>/dev/null
```

**WARNING**: with docker is mandatory edit `config.js` and set `chrome_headless` on `true` and set `executable_path` to `/usr/bin/chromium-browser`. Without this fix docker don't work.

**Comment by AleTassi** [comment]
I runned `npm install`.
`node bot.js` should work too, in the bot.js file I see 
```
const config_file = (argv.config ? argv.config : "./configs/config.js");
```
so it should take the config file.
Anyway, it does the same error even running `node bot.js --config="./configs/config.js"`

**Comment by AleTassi** [comment]
I tryed now, the logs keep saying to me `Error: Cannot find module 'yargs'`

**Comment by ptkdev** [comment]
@AleTassi finally docker hub rebuild app (after 22 hours!!!) try now.

**Comment by AleTassi** [comment]
Almost working ahahaha
```
[2018-09-28T10:48:51.296Z] PM2 log: Launching in no daemon mode
[2018-09-28T10:48:51.401Z] PM2 log: Starting execution sequence in -fork mode- for app name:bot id:0
[2018-09-28T10:48:51.409Z] PM2 log: App name:bot id:0 online
[INFO] utils: loginpin.txt created
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log created
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
[INFO] login: loading...
[INFO] login: open_loginpage
[INFO] utils: Bot is updated! :D
[INFO] login: set_username
[INFO] login: set_password
[INFO] login: submit
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/app/node_modules/puppeteer/lib/ElementHandle.js:86:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by ptkdev** [comment]
Now problem is error of HTMLElement. This happen becouse docker contain chromium v68 but bot need chromium v69 😩😩😩

**Comment by ptkdev** [comment]
Updated docker files
