### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by gkarmas** [social-manager-tools/instagram-bot.js#131]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.9.1
- **Node Version:** v6.14.4
- **Operating System:** Ubuntu 14.04
- **Browser:** No Browser. SSH.

### Expected Behavior

To Run.

### Actual Behavior

By Running:

`node bot.js --config="./configs/config.js"`

I am getting:

```
/home/botuser/instabot/node_modules/instagrambotlib/lib.js:32
    this.stop = async function () {
                      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/botuser/instabot/bot.js:30:13)
```

### Steps to Reproduce

Install on ubuntu with specified node version and test. I tried on 2 servers, no luck.

### config.js (remember to remove password)
```
odule.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools
    // Instagram Account
    "instagram_username": "myuser", // without @
    "instagram_password": "mypass",
    "instagram_hashtag": ["twitch", "fortnite", "art", "love", "gaming", "streamer", "design", "nature", "twitchst$
    "instagram_pin": "sms", //method to receive pin (email or sms)
    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last $
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep $
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same u$
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-2$
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop).$
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 800,      // work in all likemode_*
    "bot_likeday_max": 900,      // work in all likemode_*. In 2018 limit instagram is 1000/day
    "bot_sleep_night": false,    // if you need stop bot in night
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemod$
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit ins$
    "bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work $
    "bot_userwhitelist": ["test", "test2", "test3"],   // usernames without @ | don't defollow this u$
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["cool", "nice", "💜💜", "💜"],
        }
    },
    "likemode_competitor_users": {
        "account": "someaccount" // without @
    },
    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1024x768"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report
    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};
```

**Comment by ptkdev** [comment]
Bot don't support node <= **`v7.6`**

**Comment by gkarmas** [comment]
Thanks @ptkdev I tried on node v8.0.0 and v8.12.0 - different error
```
(node:2912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '/home/botuser/instabot/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
(node:2912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ptkdev** [comment]
Try `sudo npm install sqllite3 -g` and `npm install`

**Comment by ptkdev** [comment]
I test bot with latest version of Ubuntu LTS, Debian, Archlinux, Mac OSX and Windows 10. 

Is hard support old version of Ubuntu 14.XX but if work this solution I'm happy

**Comment by ptkdev** [comment]
Another possibile solution is install chromium package from apt :) chromium install all dependieces of puppeteer
