### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by dropitlikecross** [social-manager-tools/instagram-bot.js#143]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.9.1
- **Node Version:** v8.10.0 (Bot require >= 7.6)
- **Operating System:** Ubuntu 18.04
- **Browser:** Google Chrome 64

### Actual Behavior

```
instabot@instabot:~/instagram-bot.js$ node bot.js --config="./configs/config.js"
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
(node:9202) UnhandledPromiseRejectionWarning: Error: target_count_per_day must be positive
    at Utils.compute_interval_between_run_in_seconds (/home/instabot/instagram-bot.js/node_modules/instagrambotlib/modules/common/utils.js:131:19)
    at Utils.fixconfig (/home/instabot/instagram-bot.js/node_modules/instagrambotlib/modules/common/utils.js:350:43)
    at module.exports.start (/home/instabot/instagram-bot.js/node_modules/instagrambotlib/lib.js:76:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```
```
```
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "someusername", // without @
    "instagram_password": "abc123",
    "instagram_hashtag": ["edm", "monstercat", "edc"], //without #, recommended more than 20
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 800,      // work in all likemode_*
    "bot_likeday_max": 900,      // work in all likemode_*. In 2018 limit instagram is 1000/day
    "bot_sleep_night": false,    // if you need stop bot in night
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 1,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 1,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
    "bot_userwhitelist": ["user1", "user2", "user3"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["comment1", "comment2", "comment3"],
        }
    },
    "likemode_competitor_users": {
        "account": "user_nickname" // without @
    },

    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1024x768"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};
```


```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Set `bot_followday` > 1, if you don't use fdfmode this value is ignored.
