### ISSUE TITLE
Error on Raspbian 9

### ISSUE THREAD

**Issue by chinciusan** [social-manager-tools/instagram-bot.js#144]
### Versions

Replace the values below with your own:

- **Bot Version:** v1.0.0
- **Node Version:** v11.4.0 (Bot require >= 7.6)
- **Operating System:** Raspbian 
- **Browser:** Chromium 65.0.3325.181 Built on Raspbian , running on Raspbian 9.6

### Expected Behavior

Please describe the program's expected behavior.

```
Start the bot
```

### Actual Behavior

Errors out after submitting password. 
```
[INFO] login: open_loginpage
[INFO] login: set_username
[INFO] login: set_password
[INFO] login: submit
(node:21000) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/home/pi/projects/instabot/node_modules/puppeteer/lib/ElementHandle.js:91:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:21000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chinciusan** [comment]
I was using the old version of Chromium. Updating it to v69 makes it work.
