### ISSUE TITLE
Docker Error on Raspberry PI 3B: Cannot find module ./configs/config.js

### ISSUE THREAD

**Issue by jorrharris** [social-manager-tools/instagram-bot.js#147]
### Versions

Replace the values below with your own:

* **Bot Version:** v0.9.1
* **Node Version:** not sure, just bought my rpi3
* **Operating System:** Raspbian 9 (Strech)
* **Browser:** Chromium

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
2019-02-26T08:07:57: PM2 log: App [bot:0] starting in -fork mode-
2019-02-26T08:07:57: PM2 log: App [bot:0] online
Error: Cannot find module './configs/config.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
2019-02-26T08:08:00: PM2 log: App [bot:0] exited with code [1] via signal [SIGINT]
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/bot.js:35:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. docker run --restart=always --name=sceneitknowit -d -v /usr/bin/pi/Desktop/sceneitknowit/config.js:/app/configs/config.js socialmanagertools/instagram-bot.js:armv7
2. docker logs --tail 50 --follow sceneitknowit

### config.js (remember to remove password)
```
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools
    // Instagram Account
    "instagram_username": "userhere", // without @
    "instagram_password": "passwordhere",
    "instagram_hashtag": ["picoftheday", "scenery", "sunset", "sunsets", "beautiful", "landscape"], //without #, recommended more than 20
    "instagram_pin": "sms", //method to receive pin (email or sms)
    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
    "bot_mode": "likemode_superlike",
    "bot_likeday_min": 400,      // work in all likemode_*
    "bot_likeday_max": 450,      // work in all likemode_*. In 2018 limit instagram is 1000/day
    "bot_sleep_night": true,    // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 2,        // superlike number of likes for user
    "bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
    "bot_userwhitelist": ["user1", "user2", "user3"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["comment1", "comment2", "comment3"],
        }
    },
    "likemode_competitor_users": {
        "account": "user_nickname" // without @
    },
    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1024x768"],
    "executable_path": "/usr/bin/chromium-browser", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report
    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Copy your config to `/configs/` directory and remember to remove `.tpl` suffix. 
imho you need run: `mv ./configs/config.js.tpl ./configs/config.js`
