### ISSUE TITLE
Error during start - Promise Rejection

### ISSUE THREAD

**Issue by N8teZero** [social-manager-tools/instagram-bot.js#61]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.7.5
- **Node Version:** v8.10 (Bot require >= 7.6)
- **Operating System:** Windows 10
- **Browser:** Google Chrome 64

### Expected Behavior

Before updating, the bot started up without issue. Ensured all files were updated and filled in the config. 

```

```

### Actual Behavior

Bot crashes during start function. Using realistic mode. 

```
[INFO] twofa: starting current mode
[INFO] twofa: status: 0                                                                                                                                                      
[INFO] like_realistic: realistic                                                                                                                                             
[INFO] like_realistic: time night: 1816                                                                                                                                      
(node:8372) UnhandledPromiseRejectionWarning: TypeError: this.config.bot_sleep_night.replace is not a function                                                               
    at Likemode_realistic.start (C:\Users\~\Desktop\instagram-bot.js\modules\likemode_realistic.js:154:142)                                                              
    at switch_mode (C:\Users\~\Desktop\instagram-bot.js\bot.js:89:48)                                                                                                    
    at start (C:\Users\~\Desktop\instagram-bot.js\bot.js:118:19)                                                                                                         
    at <anonymous>                                                                                                                                                           
(node:8372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)                                                                                                   
(node:8372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                                                                                                                                               
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```
module.exports = {
    // InstagramBot.js Configs
    "debug": false,
    "login": true,

    // Instagram Account
    "instagram_username": "~", // without @
    "instagram_password": "~",
    "instagram_hashtag": ['clubloose','formulad'], //without #
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [TEST] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [TEST] fdfmode_classic           - follow user from random hashtag and defollow after 1h | 300 follow-defollow/day.
    // [TEST] comment_mode              - leave a comment under the photo via hashtag.
    // [TODO] fdfmode_defollowall       - defollow all your following (not defollow users in whitelist) | 30 defollow/hour.
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 400,
    "bot_likeday_max": 600,      // in 2018 limit instagram is descreased to 400-600/day :(
    "bot_sleep_night": "7:00",   // sleep from 00:00 to 7:00 am, work only in likemode_realistic and comment_mode
    "bot_fastlike_min": "15",    // min minutes of sleep after like 10-12 photo, work only in likemode_realistic
    "bot_fastlike_max": "20",    // max minutes of sleep after like 10-12 photo, work only in likemode_realistic
    "bot_followday": 300,        // follow-defollow user/day, work only in fdfmode_classic
    "bot_userwhitelist": [""],   // usernames without @ | don't defollow this users on follow-defollow mode, work only in all fdfmode_*
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": [],
        }
    },
    "likemode_competitor_users": {
        "account": "", // without @
    },

    // Puppeteer Configs
    "chrome_headless": false,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // LOG
    "log": {
        "drivers": ["console"], // slack or console
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};
```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Hi!
Update your `config.js` file from `config.js.tpl `

Remove:
```
"bot_sleep_night": "7:00",
```
Add:
```
"bot_sleep_night": true,     // if you need stop bot in night 
"bot_start_sleep": "7:00",
```
<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
