### ISSUE TITLE
Uploaded bot in Heroku but it keeps crashing while it works locally.

### ISSUE THREAD

**Issue by zacharisharris** [social-manager-tools/instagram-bot.js#64]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.8.0
- **Node Version:** v8.11.3 (Bot require >= 7.6)
- **Operating System:** Windows 10
- **Browser:** Google Chrome 64

### Expected Behavior

Please describe the program's expected behavior.

I followed all the steps correctly and the bot worked like a charm in Powershell. Though, I want it to run all day so I uploaded it to Heroku, added a Procfile with the worker: node bot.js so it will run as a background proccess but it keeps crashing with an error. (It is running headless). It only crashes in Heroku, Powershell keeps working fine. What is wrong?

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The log of the error is the following:

 internal/modules/cjs/loader.js:583
2018-07-18T19:49:15.903335+00:00 app[worker.1]:     throw err;
2018-07-18T19:49:15.903337+00:00 app[worker.1]:     ^
2018-07-18T19:49:15.903338+00:00 app[worker.1]: 
2018-07-18T19:49:15.903339+00:00 app[worker.1]: Error: Cannot find module './config'
2018-07-18T19:49:15.903355+00:00 app[worker.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2018-07-18T19:49:15.903357+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2018-07-18T19:49:15.903366+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:637:17)
2018-07-18T19:49:15.903368+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:20:18)
2018-07-18T19:49:15.903369+00:00 app[worker.1]:     at Object.<anonymous> (/app/bot.js:35:16)
2018-07-18T19:49:15.903370+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
2018-07-18T19:49:15.903372+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2018-07-18T19:49:15.903373+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:599:32)
2018-07-18T19:49:15.903374+00:00 app[worker.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2018-07-18T19:49:15.903375+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2018-07-18T19:49:15.903355+00:00 app[worker.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2018-07-18T19:49:15.903357+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2018-07-18T19:49:15.903366+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:637:17)
2018-07-18T19:49:15.903368+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:20:18)
2018-07-18T19:49:15.903369+00:00 app[worker.1]:     at Object.<anonymous> (/app/bot.js:35:16)
2018-07-18T19:49:15.903370+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
2018-07-18T19:49:15.903372+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2018-07-18T19:49:15.903373+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:599:32)
2018-07-18T19:49:15.903374+00:00 app[worker.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2018-07-18T19:49:15.903375+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)

module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "hiddentreasur3s", // without @
    "instagram_password": "PWD",
    "instagram_hashtag": ["instabeach", "like4like", "follow4follow"], //without #
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [TODO] fdfmode_classic           - follow user from random hashtag and defollow after 1h | 300 follow-defollow/day.
    // [TODO] fdfmode_defollowall       - defollow all your following (not defollow users in whitelist) | 30 defollow/hour.
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 400,      // work only in likemode_classic
    "bot_likeday_max": 600,      // work only in likemode_classic. In 2018 limit instagram is descreased to 400-600/day :(
    "bot_sleep_night": true,     // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_fastlike_min": "15",    // min minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 50min)
    "bot_fastlike_max": "20",    // max minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 60min)
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // follow-defollow user/day, work in fdfmode_classic and fdfmode_defollowall
    "bot_userwhitelist": [""],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic and fdfmode_defollowall
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": [],
        }
    },
    "likemode_competitor_users": {
        "account": "", // without @
    },

    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // LOG
    "pin_path":"./loginpin.txt",
    "log_path":"./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path":"./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
‘Error: Cannot find module './config‘
Rename’config.js.tpl’to ‘config.js‘ and fill it

**Comment by ptkdev** [comment]
<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
