### ISSUE TITLE
Failed to Launch Chrome

### ISSUE THREAD

**Issue by focamonca** [social-manager-tools/instagram-bot.js#81]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.9.0
- **Node Version:** lastest
- **Operating System:** Raspbian 9
- **Browser:** chromium

### Expected Behavior

Please describe the program's expected behavior.

```
The bot should run
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
when I run node bot.js I get

`node bot.js
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
(node:5400) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/pi/Desktop/instabotjs/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: 1: /home/pi/Desktop/instabotjs/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: Syntax error: word unexpected (expecting ")")


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/pi/Desktop/instabotjs/node_modules/puppeteer/lib/Launcher.js:299:14)
    at Interface.helper.addEventListener (/home/pi/Desktop/instabotjs/node_modules/puppeteer/lib/Launcher.js:288:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
(node:5400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[WARNING] utils: Bot release v0.9.0-b available! Current version: v0.9.0
`

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. cd Desktop/instabotjs
2. node bot.js

### config.js (remember to remove password)
```
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "", // without @
    "instagram_password": "",
    "instagram_hashtag": ["instagram", "muraleshunter", "hashtag"], //without #, raccomanded more than 20
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 800,      // work only in likemode_classic
    "bot_likeday_max": 900,      // work only in likemode_classic. In 2018 limit instagram is 1000/day
    "bot_sleep_night": false,    // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
    "bot_userwhitelist": ["giulyegiammy", "powerslidelover", "ste_tami"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["comment1", "comment2", "comment3"],
        }
    },
    "likemode_competitor_users": {
        "account": "user_nickname" // without @
    },

    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};


```

### Screenshots (Optional)

![image](https://user-images.githubusercontent.com/19846692/45436151-659caa00-b6b2-11e8-875e-d49a16729bb0.png)

**Comment by ptkdev** [comment]
## Please use latest version **v0.9.0c**
Log see message: `[WARNING] utils: Bot release v0.9.0-b available! Current version: v0.9.0`

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>

**Comment by focamonca** [comment]
Thanks, sorry for stupid question

**Comment by focamonca** [comment]
Is there a way to update it without the need to configure the files again?

**Comment by ptkdev** [comment]
@focamonca nothing is stupid, `npm update` or `npm install instagrambot@0.9.0b`
