### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Timed out after 30000 ms while trying to connect to Chrome!

### ISSUE THREAD

**Issue by marcopolo88** [social-manager-tools/instagram-bot.js#94]
chromedriver is unzipped
root@instapy1:/home/instapy1/instagram-bot.js/instagram-bot.js-0.9.3# chmod +x chromedriver
root@instapy1:/home/instapy1/instagram-bot.js/instagram-bot.js-0.9.3# chmod 755 chromedriver
root@instapy1:/home/instapy1/instagram-bot.js/instagram-bot.js-0.9.3# node bot.js

Bot Version: v0.9.3
Node Version: v8.2 (Bot require >= 7.6)
Operating System: Ubuntu 18.04
Browser: Google Chrome 64
https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
Expected Behavior
starting

Actual Behavior
not starting (timeout)

Steps to Reproduce
Please include the steps the reproduce the issue, numbered below. Include as much detail as possible.

starting bot
see bot not started

TERMINAL
root@instapy1:/home/instapy1/instagram-bot.js/instagram-bot.js-0.9.3# node bot.js
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
[INFO] utils: Bot is updated! :D
**(node:5190) UnhandledPromiseRejectionWarning: Error: Timed out after 30000 ms while trying to connect to Chrome!** The only Chrome revision guaranteed to work is r555668
    at Timeout.onTimeout (/home/instapy1/instagram-bot.js/instagram-bot.js-0.9.3/node_modules/puppeteer/lib/Launcher.js:266:14)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:5190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
root@instapy1:/home/instapy1/instagram-bot.js/instagram-bot.js-0.9.3# chromedriver
Starting ChromeDriver 2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac) on port 9515
Only local connections are allowed.
^C
TERMINAL

`
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "", // without @
    "instagram_password": "",
    "instagram_hashtag": ["sdsf", "sfasf", "saffsf"], //without #, raccomanded more than 20
    "instagram_pin": "email", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialb$
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 800,      // work only in likemode_classic
    "bot_likeday_max": 900,      // work only in likemode_classic. In 2018 limit instagram is 1000/day
    "bot_sleep_night": true,    // if you need stop bot in night
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all$
    "bot_userwhitelist": ["user1", "user2", "user3"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {        "type": "array",
            "source": [ 'Awesome', 'Nice one', 'sweet', ':)', 'Nice','Top stuff','Love your work! :)','Great pic','We love your page, send us a message if youd like to organise something :$
        }
    },
    "likemode_competitor_users": {
        "account": "user_nickname" // without @
    },

    // Puppeteer Configs
    "chrome_headless": false,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "/home/instapy1/instagram-bot.js/instagram-bot.js-0.9.3/chromedriver", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }

`

**Comment by ptkdev** [comment]
Why you download chromedriver and set chromedriver to path? Where you read this on readme?
You need real browser path (chromium or google chrome path). 

`executable_path` is mandatory on raspberry pi, is optional on windows/linux/mac (library download automatically chrome). You don't need set executable_path on ubuntu.

**Comment by ptkdev** [comment]
Try [Social Manager Tools](https://socialmanagertools.ptkdev.io/) for Windows, Mac and Linux. GUI Version of bot, is more easy than library.

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>

**Comment by marcopolo88** [comment]
installed chromium-bsu package earlier and still getting
`
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
(node:5633) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

(chrome:5644): Gtk-WARNING **: 20:43:33.523: cannot open display:
`

**Comment by marcopolo88** [comment]
thx but I think i pass the windows tools
https://www.virustotal.com/#/file/5d7d0d6884c31238fd29b1894f95cfc853d02f6bf346f230ff4925d920add972/detection

**Comment by ptkdev** [comment]
Set `executable_path` to empty value, example: `executable_path:""`
`chromium-bsu` don't is browser,  `chromium-browser` package is browser on ubuntu.

Is normal if **virustotal** detect this bot at virus, IS A BOT... If you [open detail](https://www.virustotal.com/#/file/5d7d0d6884c31238fd29b1894f95cfc853d02f6bf346f230ff4925d920add972/details) of virus total is becouse app is'nt signed. Why? I don't have microsoft developer account for signed this app. 

@marcopolo88  Social manager tools NOT contains:
- Keylogger
- Virus
- Bitcoin miner
And NOT save password on cloud or server. Is open source = all code is showed at all, nothing is secret on actions of this bot.
