### ISSUE TITLE
Dockerizing the bot

### ISSUE THREAD

**Issue by AleTassi** [social-manager-tools/instagram-bot.js#95]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.9.3
- **Node Version:** v8.12 (Bot require >= 7.6)
- **Operating System:** Windows 10 home
- **Browser:** Google Chrome 64

### Expected Behavior

I try to dockerize, running the command 
```
docker run --name=instagram-bot -d -v /configs/config.js:/app/configs/config.js socialmanagertools/instagram-bot.js
```
should pull the image from the repository and start using the local config.js

### Actual Behavior
-In the docker volume is created a folder "/app/configs/config.js", the confi.js is not a file, is a folder.
-I moved the original config.js instead of the folder and docker showed those logs:
```
2018-09-25T09:29:41.609Z] PM2 log: App name:bot id:0 online
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome ENOENT
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:255:14)
    at ChildProcess.helper.addEventListener.error (/app/node_modules/puppeteer/lib/Launcher.js:246:64)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:362:16)
    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[INFO] utils: Bot is updated! :D
[2018-09-25T09:29:42.786Z] PM2 log: App [bot] with id [0] and pid [29], exited with code [0] via signal [SIGINT]
[2018-09-25T09:29:42.790Z] PM2 log: Starting execution sequence in -fork mode- for app name:bot id:0
[2018-09-25T09:29:42.795Z] PM2 log: App name:bot id:0 online
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome ENOENT
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:255:14)
    at ChildProcess.helper.addEventListener.error (/app/node_modules/puppeteer/lib/Launcher.js:246:64)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:362:16)
    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[INFO] utils: Bot is updated! :D
```
Repetedly

### Steps to Reproduce

1. Git clone the repository from github
2. ```npm install```
4. modify the config.js file
3. ```docker run --name=instagram-bot -d -v /configs/config.js:/app/configs/config.js socialmanagertools/instagram-bot.js```
The bot work perfectly via the node bot.js command. My docker works too for other project.

### config.js (remember to remove password)
```
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "usr", // without @
    "instagram_password": "pw",
    "instagram_hashtag": ["italianguy", "italiano", "italianboy", "ragazzo", "ragazzoita"], //without #, raccomanded more than 20
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
    "bot_mode": "likemode_superlike",
    "bot_likeday_min": 800,      // work only in likemode_classic
    "bot_likeday_max": 900,      // work only in likemode_classic. In 2018 limit instagram is 1000/day
    "bot_sleep_night": false,    // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
    "bot_userwhitelist": ["usr"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["comment1", "comment2", "comment3"],
        }
    },
    "likemode_competitor_users": {
        "account": "user_nickname" // without @
    },

    // Puppeteer Configs
    "chrome_headless": false,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};
```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
On docker is mandatory hide browser, docker = no monitor. 
Set `chrome_headless` to **`true`**

**Comment by AleTassi** [comment]
I copyed the wrong config.js, I set that to true, but the same error appear. sorry

**Comment by ptkdev** [comment]
@julianxhokaxhiu please help me with this issue

**Comment by julianxhokaxhiu** [comment]
I'll assign this issue to myself as a reminder. I'll provide later some feedback.

**Comment by AleTassi** [comment]
> > -In the docker volume is created a folder "/app/configs/config.js", the confi.js is not a file, is a folder.
> > -I moved the original config.js instead of the folder and docker showed those logs:
> 
> @AleTassi you should mount the file, not a directory. At the current status the container is not even reading your file, but is using the safe defaults. This is why it is not working.
> 
> Please fix your volume mount and ping back again if the error persists.

I did, I deleted the folder, i mooved in the file and restarted the image, without those moves docker gave me an error like ":/configs/config not found", but mooving in the real config file i get the error copyed before

**Comment by ptkdev** [comment]
@AleTassi we rebuild docker with possible patch. Retry download docker container.

**Comment by AleTassi** [comment]
deleted the image, rerunned the command,

`[2018-09-26T18:02:39.986Z] PM2 log: Launching in no daemon mode


[2018-09-26T18:02:40.040Z] PM2 log: Starting execution sequence in -fork mode- for app name:bot id:0


[2018-09-26T18:02:40.046Z] PM2 log: App name:bot id:0 online


[INFO] utils: loginpin.txt created


[INFO] utils: logs/debug.log exist


[INFO] utils: logs/errors.log created


[INFO] utils: databases/fdf.db exist


[INFO] utils: databases/logs.db exist


[WARNING] utils: Bot work? Please donate for support this project!


[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io


[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io


You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:


Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md


    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:255:14)


    at ChildProcess.helper.addEventListener.error (/app/node_modules/puppeteer/lib/Launcher.js:246:64)


    at emitOne (events.js:116:13)


    at ChildProcess.emit (events.js:211:7)


    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)


    at onErrorNT (internal/child_process.js:362:16)


    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)


    at _combinedTickCallback (internal/process/next_tick.js:139:11)


    at process._tickDomainCallback (internal/process/next_tick.js:219:9)


[INFO] utils: Bot is updated! :D


[2018-09-26T18:02:41.153Z] PM2 log: App [bot] with id [0] and pid [20], exited with code [0] via signal [SIGINT]


[2018-09-26T18:02:41.155Z] PM2 log: Starting execution sequence in -fork mode- for app name:bot id:0


[2018-09-26T18:02:41.161Z] PM2 log: App name:bot id:0 online


[INFO] utils: loginpin.txt exist


[INFO] utils: logs/debug.log exist


[INFO] utils: logs/errors.log exist


[INFO] utils: databases/fdf.db exist


[INFO] utils: databases/logs.db exist


[WARNING] utils: Bot work? Please donate for support this project!


[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io


[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io


You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:


Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md


    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:255:14)


    at ChildProcess.helper.addEventListener.error (/app/node_modules/puppeteer/lib/Launcher.js:246:64)


    at emitOne (events.js:116:13)


    at ChildProcess.emit (events.js:211:7)


    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)


    at onErrorNT (internal/child_process.js:362:16)


    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)


    at _combinedTickCallback (internal/process/next_tick.js:139:11)


    at process._tickDomainCallback (internal/process/next_tick.js:219:9)


[INFO] utils: Bot is updated! :D


[2018-09-26T18:02:42.272Z] PM2 log: App [bot] with id [0] and pid [34], exited with code [0] via signal [SIGINT]


[2018-09-26T18:02:42.273Z] PM2 log: Starting execution sequence in -fork mode- for app name:bot id:0


[2018-09-26T18:02:42.276Z] PM2 log: App name:bot id:0 online`

same error

**Comment by julianxhokaxhiu** [comment]
Can you please try to change this `config.js` line, from
```
"chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
```
to
```
"chrome_options": ["--disable-gpu", "--no-sandbox", "--disable-setuid-sandbox", "--window-size=1920x1080"],
```
and report back? Thanks.

**Comment by julianxhokaxhiu** [comment]
Thanks, then please try setting this:
```
"executable_path": "/usr/bin/chromium-browser"
```
and report back

**Comment by AleTassi** [comment]
working perfectly with that, thank you !

**Comment by julianxhokaxhiu** [comment]
Welcome :)

**Comment by ptkdev** [comment]
Updated README.md with new config.js params (mandatory)
